### ISSUE TITLE
Stray goroutine when ctrl-c is used to quit

### ISSUE THREAD

**Issue by tomsrobots** [phux/pomogoro#10]
I gave pomogoro a shot for the first time and in general I really like it. However, when I issued ctrl-c to quit as per the instruction and tried to boot pomogoro back up, I got the following:
```panic: Near line 0 (last key parsed ''): bare keys cannot contain '('

goroutine 1 [running]:
github.com/phux/pomogoro/config.Load(0x7ffc62f5cbdc, 0x18, 0x2, 0x2, 0x0)
	/home/username/Development/Go/src/github.com/phux/pomogoro/config/config.go:41 +0x2af
main.main()
	/home/username/Development/Go/src/github.com/phux/pomogoro/main.go:30 +0xf0
```

**Comment by phux** [comment]
Glad you like it :)

Regarding the issue:
The error indicates that there is a problem with decoding the config file.
Could you paste the contents here?

**Comment by tomsrobots** [comment]
Sure! I should say I have never used Go before and installed it just for your project. It's possible I set something up wrong. Here's my config file:
```
# config.toml
TodoFile = "/home/username/todo.txt" # containing the tasks you want to track
LogFile = "/home/username/.config/pomogoro/pomogoro.log" # tracking log file
BreakDuration = 5 # in minutes
PomodoroEnabled = true # whether to use pomodoro timer or not
PomodoroDuration = 25 # in minutes
LogIdleTime = true # also log idle times
LogBreakTime = true # also log breaks
```

**Comment by jmollowitz-EP** [comment]
Weird, your config looks okay, I can also start pomogoro with your config via
```sh
pomogoro --config /tmp/toms_config.toml
```
Maybe try [downloading the latest release](https://github.com/phux/pomogoro/releases/tag/v1.4.0) for your OS?

**Comment by phux** [comment]
Weird, your config looks okay, I can also start pomogoro with your config via
```sh
pomogoro --config /tmp/toms_config.toml
```
Maybe try [downloading the latest release](https://github.com/phux/pomogoro/releases/tag/v1.4.0) for your OS instead of using the go installation (then you can also remove go from your OS)?
